In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.io import loadmat
%matplotlib inline

In [6]:
data = loadmat('F:\\mldata\\ex3data1 (2)')

In [7]:
X = data['X']
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [8]:
y = data['y']
y

array([[10],
       [10],
       [10],
       ...,
       [ 9],
       [ 9],
       [ 9]], dtype=uint8)

## DecisionTreeClassifier

In [11]:
from sklearn.tree import DecisionTreeClassifier

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=100)

In [14]:
dt=DecisionTreeClassifier(criterion='gini',max_depth=20,max_features=50)
dt.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=20,
                       max_features=50, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [15]:
dt

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=20,
                       max_features=50, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [16]:
y_pred=dt.predict(X_test)

In [17]:
y_pred.shape

(1500,)

In [18]:
dt.score(X_train,y_train)

1.0

In [19]:
dt.score(X_test,y_test)                  

0.732

## LogisticRegression

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=100)

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
lr=LogisticRegression()

## RandomForestClassifier

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
rf=RandomForestClassifier(n_estimators=100)

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=100)

In [31]:
rf.fit(X_train,y_train)#.raval

C:\Users\dell\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [32]:
rf.score(X_test,y_test)                    

0.9253333333333333

## BaggingClassifier

In [33]:
from sklearn.ensemble import BaggingClassifier

In [34]:
dc=BaggingClassifier(base_estimator=DecisionTreeClassifier(),n_estimators=100)

In [35]:
dc.fit(X_train,y_train)

C:\Users\dell\Anaconda\lib\site-packages\sklearn\ensemble\bagging.py:623: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort=False,
                                                        random_state=None,
                                                        splitter='best'),
    

In [36]:
dc.score(X_train,y_train)

1.0

In [37]:
dc.score(X_test,y_test)                    

0.902

## GradientBoostingClassifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
gbc=GradientBoostingClassifier(learning_rate=0.1,n_estimators=1000)

In [ ]:
gbc.fit(X_train,y_train)

In [ ]:
gbc.score(X_test,y_test),gbc.score(X_train,y_train)          

## AddaBoostClassifier

In [ ]:
from sklearn.ensemble import AddaBoostClassifier

In [ ]:
abc=AddaBoostClassifier(n_estimators=1000,base_estimator=DecisionTree)

In [ ]:
abc.fit(X_train,y_train)

In [ ]:
abc.score(X_test,y_test),abc.score(X_train,y_train)          

## XGBClassifier

In [12]:
from xgboost import XGBClassifier

In [13]:
model = XGBClassifier()
model.fit(X_train, y_train)

C:\Users\dell\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\dell\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method=None, validate_parameters=False, verbosity=None)

In [14]:
model.score(X_test,y_test),model.score(X_train,y_train)          

(0.926, 1.0)

In [3]:
data = loadmat('F:\\mldata\\ex3data1 (2)')
data

NameError: name 'loadmat' is not defined

In [ ]:
type(data)

In [2]:
X = data['X']
X

NameError: name 'data' is not defined

In [ ]:
X = np.insert(X,0,1,axis = 1)
X

In [28]:
X.shape

(5000, 401)

In [29]:
X[0,200:210]   #checking the first row 

array([ 0.00000000e+00,  0.00000000e+00, -7.03635621e-04, -1.27262443e-02,
        1.61706648e-01,  7.79865383e-01,  1.03676705e+00,  8.04490400e-01,
        1.60586724e-01, -1.38173339e-02])

In [30]:
type(X)

numpy.ndarray

In [ ]:
y = data['y']
y

In [32]:
type(y)

numpy.ndarray

In [33]:
y.shape

(5000, 1)

In [34]:
np.unique(y)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=uint8)

In [35]:
X = np.matrix(X)
X

matrix([[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]])

In [36]:
X.shape

(5000, 401)

In [37]:
y = np.matrix(y)
y

matrix([[10],
        [10],
        [10],
        ...,
        [ 9],
        [ 9],
        [ 9]], dtype=uint8)

In [38]:
y.shape

(5000, 1)

In [39]:
type(list)

type

In [40]:
theta = np.zeros((1,401))
theta

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [41]:
theta.shape

(1, 401)

In [23]:
theta = np.matrix(theta)
theta

matrix([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [24]:
theta.shape

(1, 401)

In [25]:
def sigmoid(z):
    a = 1/(1+np.exp(-z))
    return a 

In [26]:
sigmoid(0)

0.5

In [27]:
def computeCost1(X,y,theta):
    first = np.multiply(-y,np.log(sigmoid(X*theta.T)))
    second = np.multiply((1-y),np.log(1-sigmoid(X*theta.T)))
    return np.sum(first-second)/len(X)
computeCost1(X,y,theta)

-17.051420641774662

In [28]:
def gradientDescent(X,y,theta,alpha,iters):
    temp = np.matrix(np.zeros((1,401)))
    parameters = 401
    cost = np.zeros(iters)
    
    for i in range(iters):
        error = sigmoid(X*theta.T)-y
#         print(i)
        
        for j in range(parameters):
#             print(j)
            term = np.multiply(error,X[:,j])
            temp[0,j]=theta[0,j]-((alpha/len(X))*np.sum(term))
            
        theta = temp
        #cost[i] = computeCost1(X,y,theta)
    return theta
#a,b = gradientDescent(X,y,theta,0.01,10)

In [29]:
all_theta=np.matrix(np.zeros((10,401)))   #thetas 
for i in range(1,11):
    new_y=np.zeros(len(y))
        
    for j in range(len(y)):
        if(y[j]==i):
            new_y[j]=1
        else:
            new_y[j]=0
    new_y = np.matrix(new_y)
    all_theta[i-1,:]=gradientDescent(X,new_y.T,theta,0.1,10)

In [30]:
all_theta

matrix([[-1.03878632e-01,  0.00000000e+00,  0.00000000e+00, ...,
         -4.60083766e-07,  6.25268075e-08,  0.00000000e+00],
        [-1.22000553e-01,  0.00000000e+00,  0.00000000e+00, ...,
          4.16316657e-06, -3.40309138e-07,  0.00000000e+00],
        [-1.22665454e-01,  0.00000000e+00,  0.00000000e+00, ...,
         -7.89523333e-07,  7.02034966e-08,  0.00000000e+00],
        ...,
        [-1.28376566e-01,  0.00000000e+00,  0.00000000e+00, ...,
         -8.46803137e-07,  7.56980459e-08,  0.00000000e+00],
        [-1.18933252e-01,  0.00000000e+00,  0.00000000e+00, ...,
         -8.21533271e-07,  7.46521880e-08,  0.00000000e+00],
        [-1.27630120e-01,  0.00000000e+00,  0.00000000e+00, ...,
         -2.54222828e-06,  8.11878058e-08,  0.00000000e+00]])

In [31]:
all_theta.shape

(10, 401)

In [32]:
X.shape

(5000, 401)

In [33]:
p = sigmoid(X*all_theta.T)
p

matrix([[0.05783686, 0.09067937, 0.10015133, ..., 0.0971875 , 0.07983084,
         0.28876148],
        [0.05166965, 0.07207105, 0.08663473, ..., 0.07699016, 0.06267731,
         0.252404  ],
        [0.03065327, 0.04998808, 0.05744311, ..., 0.06655598, 0.04368845,
         0.07903604],
        ...,
        [0.1735744 , 0.18934471, 0.21732566, ..., 0.21399155, 0.23893025,
         0.17474773],
        [0.04223821, 0.04650669, 0.04464553, ..., 0.06829688, 0.09097715,
         0.06468728],
        [0.05500975, 0.113627  , 0.08328352, ..., 0.10255931, 0.10363938,
         0.16590437]])

In [34]:
p.shape

(5000, 10)

In [35]:
y_pred = np.zeros((5000,1))
y_pred = np.argmax(p,axis = 1) + 1 

In [36]:
y_pred

matrix([[10],
        [10],
        [10],
        ...,
        [ 9],
        [ 9],
        [10]], dtype=int64)

In [37]:
def accuracy(y,y_pred):
    count = 0
    for j in range(len(y_pred)):
        if y[j] == y_pred[j]:
           count += 1
    return count
tc = accuracy(y,y_pred)
tc

3834

In [38]:
def accuracy():
    accuracypercentage = (tc*100)/(len(y_pred))
    return accuracypercentage
ap = accuracy()
ap

76.68